"""The standing rule: a check that reports success also reports what it examined.

    Every check shows that it examined more than zero items. A check that reports success
    must also report the number of items it looked at. A count of zero is a failure of the
    check, whatever its exit code.

WHY THIS IS A MODULE AND NOT A HABIT
------------------------------------
A test that silently examines zero items -- a loop that never ran, a filter
that matched nothing, a mutation the harness never actually collected --
still reports success, because nothing failed an assertion. Counting is the
cheapest thing that makes that impossible to do quietly, so the count is
recorded and printed rather than left to whoever reads the assertion.

HOW IT IS USED
--------------
    def test_something(examined):
        pages = collect()
        examined(len(pages), "rendered pages")
        for page in pages:
            ...

`examined` raises if the count is zero, and records it. `pytest_terminal_summary` prints
every recorded count at the end of the run, which is where the report's per-check numbers
come from -- generated by the run, never typed in by hand.

WHAT COUNTS AS A POPULATION
---------------------------
A check over a *collection* reports its size. A check asserting one named fact examines
exactly one thing and does not need telling; the rule exists for the case where a loop runs
zero times and the test passes. Where that reading is wrong, the fix is to call `examined`
in more places, not fewer -- it costs one line.
"""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class Report:
    """One check's account of what it looked at."""
    nodeid: str
    what: str
    count: int


#: Everything recorded during the session, in the order it was recorded.
RECORDS: list[Report] = []


class NothingExamined(AssertionError):
    """A check reported success over an empty population. That is a failed check."""


def record(nodeid: str, count: int, what: str) -> int:
    """Record and return `count`, refusing zero.

    Returns the count so a caller can write `n = examined(len(xs), "xs")` and keep going.
    """
    if not isinstance(count, int):
        raise NothingExamined(
            f"{nodeid}: examined() was given {count!r} ({type(count).__name__}), not a "
            f"count. The rule is about a number of items, and a truthy object is how a "
            f"zero gets past it.")
    if count <= 0:
        raise NothingExamined(
            f"{nodeid}: examined {count} {what}. A check that looks at nothing establishes "
            f"nothing, so this is a FAILURE of the check and not a pass with an empty "
            f"population. Either the fixture stopped producing items or the filter is "
            f"wrong; both are worth knowing.")
    RECORDS.append(Report(nodeid=nodeid, what=what, count=count))
    return count


def summary_lines() -> list[str]:
    """The per-check counts, and the totals, as the run's own account of its coverage."""
    if not RECORDS:
        return ["items examined: NOTHING WAS RECORDED. Either no check reported what it "
                "examined, or the recording is broken. Both are failures of the rule."]
    width = max(len(r.what) for r in RECORDS)
    lines = [f"items examined, by check ({len(RECORDS)} reports):"]
    for r in RECORDS:
        lines.append(f"  {r.count:>6}  {r.what:<{width}}  {r.nodeid}")
    total = sum(r.count for r in RECORDS)
    lines.append(f"  {total:>6}  total items examined across {len(RECORDS)} reports")
    return lines
