"""`onetrace-ci init-ci`: the no-plan path. It writes the workflow and a minimal plan, and
leaves `approved_by` as a question the gate will not pass until a person answers it."""
from __future__ import annotations

import re

import pytest
import yaml

from onetrace_ci.gate import FAIL, run_gate
from onetrace_ci.init_ci import main
from onetrace_ci.instrument import GATE_ACTION, WORKFLOW_PATH, build_patch
from tests.instrument_fixtures import PLAN, make_repo

ARGS = ["--install", "pip install --require-hashes -r requirements.lock",
        "--run", "python -m pipeline.demo", "--run-dir", "runs/{run_id}", "--baseline", "runs/baseline"]


def test_it_writes_the_workflow_and_a_minimal_plan(tmp_path, examined, capsys):
    rc = main(["--repo", str(tmp_path), *ARGS])
    plan = yaml.safe_load((tmp_path / "onetrace-plan.yaml").read_text(encoding="utf-8"))
    wf = yaml.safe_load((tmp_path / WORKFLOW_PATH).read_text(encoding="utf-8"))
    printed = capsys.readouterr().out
    examined(len(plan), "keys in the minimal plan")
    assert rc == 0
    assert set(plan) == {"approved_by", "require_declared"}
    assert plan["approved_by"].startswith("DECIDE:")
    assert plan["require_declared"] is False
    assert wf["permissions"] == {"contents": "read"}
    steps = wf["jobs"]["onetrace"]["steps"]
    assert [s["uses"] for s in steps if "uses" in s][-1] == GATE_ACTION
    gate = next(s for s in steps if s.get("name") == "onetrace-ci gate")
    assert gate["with"] == {"run": "runs/onetrace-ci-candidate", "baseline": "runs/baseline",
                            "plan": "onetrace-plan.yaml"}
    assert "DECIDE:" in printed and "approved_by" in printed


def test_the_gate_refuses_its_plan_until_approved_by_is_answered(tmp_path, make_run, examined):
    assert main(["--repo", str(tmp_path / "repo"), *ARGS]) == 0
    plan = tmp_path / "repo" / "onetrace-plan.yaml"
    baseline, run = make_run("baseline"), make_run("candidate")
    exit_code, findings = run_gate(run=run, baseline=baseline, plan_path=plan, runner=None,
                                   out=tmp_path / "out1", review_exit_zero=False)
    [open_] = [f for f in findings if f.check == "plan.approved_by"]
    assert (exit_code, open_.verdict) == (1, FAIL)

    text = plan.read_text(encoding="utf-8")
    plan.write_text(re.sub(r'approved_by: ".*"', "approved_by: alice", text), encoding="utf-8")
    exit_code, findings = run_gate(run=run, baseline=baseline, plan_path=plan, runner=None,
                                   out=tmp_path / "out2", review_exit_zero=False)
    examined(len(findings), "gate findings once approved_by is answered")
    assert exit_code == 0


@pytest.mark.parametrize("existing", ["onetrace-plan.yaml", WORKFLOW_PATH])
def test_it_never_overwrites(existing, tmp_path, examined, capsys):
    target = tmp_path / existing
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("mine\n", encoding="utf-8")
    examined(1, f"an existing {existing}")
    assert main(["--repo", str(tmp_path), *ARGS]) == 1
    assert target.read_text(encoding="utf-8") == "mine\n"
    assert "refused" in capsys.readouterr().err
    assert not (tmp_path / ("onetrace-plan.yaml" if existing == WORKFLOW_PATH else WORKFLOW_PATH)).exists()


def test_what_it_cannot_guess_is_required(tmp_path, examined):
    examined(4, "required options")
    for drop in ("--install", "--run", "--run-dir", "--baseline"):
        i = ARGS.index(drop)
        with pytest.raises(SystemExit) as caught:
            main(["--repo", str(tmp_path), *ARGS[:i], *ARGS[i + 2:]])
        assert caught.value.code == 2


def test_its_workflow_is_the_one_instrument_writes_for_the_same_ci(tmp_path, examined):
    repo = make_repo(tmp_path / "repo")
    patched = build_patch(plan_path=repo / "onetrace-plan.yaml", repo=repo).patch
    added = patched.split(f"+++ b/{WORKFLOW_PATH}\n", 1)[1]
    from_instrument = "".join(l[1:] + "\n" for l in added.splitlines() if l.startswith("+"))
    ci = re.search(r"ci:\n  install: (.*)\n  run: (.*)\n  baseline: (.*)\n", PLAN)
    other = tmp_path / "other"
    assert main(["--repo", str(other), "--install", ci.group(1), "--run", ci.group(2),
                 "--run-dir", "runs/{run_id}", "--baseline", ci.group(3)]) == 0
    from_init = (other / WORKFLOW_PATH).read_text(encoding="utf-8")
    examined(len(from_init.splitlines()), "workflow lines compared")
    #: Identical but for the first comment line, which names the command that wrote it.
    assert from_init.splitlines()[0] == "# Generated by `onetrace-ci init-ci`. It runs the pipeline, then the"
    assert from_init.splitlines()[1:] == from_instrument.splitlines()[1:]
